# Generated by Django 4.2.5 on 2023-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField(max_length=10)),
                ('Add_message', models.TextField(max_length=100)),
            ],
        ),
    ]
