# Generated by Django 4.2.5 on 2023-10-12 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appointment_phone_number_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Department',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Booked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Booking_Date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 12)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doc_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.doctors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
