# Generated by Django 4.2.5 on 2023-10-16 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_appointment_department_appointment_booked_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.IntegerField(max_length=10)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Booking_Date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 16)),
        ),
    ]
