# Generated by Django 4.2.5 on 2023-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_register_alter_appointment_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
