# Generated by Django 4.2.5 on 2023-10-19 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Booking_Date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 19)),
        ),
    ]
