# Generated by Django 4.2.5 on 2023-10-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_login_alter_appointment_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
